version: '3'

services:

  friendup-db:
    image: mariadb:10.4
    container_name: friendup-db
    env_file:
    - .env
    restart: always
    networks:
      - friendup-bridge
    expose:
      - 3306
    environment: 
      - MYSQL_INITDB_SKIP_TZINFO=1

  friendup:
    image: friendup:latest
    container_name: friendup-app
    env_file:
    - .env
    restart: always
    networks:
      - friendup-bridge
    ports:
      - 6502:6502
    volumes:
      - friendup-data:/friendup/build/storage
    depends_on:
      - friendup-db

volumes:
  friendup-data:
    driver: local

networks:
  friendup-bridge:
    driver: bridge