version: '2'

services:

  friendup-mariadb:
    image: mariadb:10.4.11
    container_name: friendup-mariadb
    restart: always
    networks:
      - friendup-bridge
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=friendupmysqlROOTpass

  friendup:
    image: friendup:latest
    container_name: friendup-app
    restart: always
    networks:
      - friendup-bridge
    ports:
      - 6502:6502
    volumes:
      - friendup-data:/friendup/build/storage
    depends_on:
      - friendup-mariadb
    environment:
      - MYSQL_USER=friendup
      - MYSQL_PASSWORD=friendup1
      - MYSQL_DATABASE=friendup
      - MYSQL_HOST=friendup-mariadb
      - MYSQL_ROOT_PASSWORD=friendupmysqlROOTpass
      - DOCKER_FRIEND_DOMAIN=example.com

volumes:
  friendup-data:
    driver: local

networks:
  friendup-bridge:
    driver: bridge